[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["oversolved*"]

[project]
name = "oversolved"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "flask",
    "waitress",
    "jax[cpu]",
    "scipy",
    "pyyaml",
    "cadquery",
    "multimethod",
    "PyMySQL",
]

[project.scripts]
oversolved = "oversolved.main:main"

[project.optional-dependencies]
dev = [
    "pytest",
    "mypy",
    "flake8",
    "pycairo",
    "just"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
markers = [
    "repeat: mark a test to be repeated multiple times",
]
filterwarnings = []

[tool.mypy]
ignore_missing_imports = true
disable_error_code = ["import-untyped"]
explicit_package_bases = true
namespace_packages = true

[tool.flake8]
max-line-length = 250
