// Collects the license text of every Rust crate compiled into the solver
// WebAssembly that ships with the app.
//
// The npm generator cannot see these: the sketch and mate solvers are built by
// wasm-pack from the Cargo workspace, and their dependencies are linked into
// public/wasm/*.wasm rather than resolved at runtime. That binary is served to
// every visitor, so nalgebra, serde and the rest are distributed exactly like
// React is, and owe the same notices.
//
// This one needs cargo and a populated registry, so it is run by hand or in CI
// rather than from a test. The test instead checks the committed bundle against
// Cargo.lock, which needs nothing installed.
//
// Usage:
//   node scripts/generateRustNotices.mjs            # write the bundle
//   node scripts/generateRustNotices.mjs --check     # fail if stale

import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const scriptDir = path.dirname(fileURLToPath(import.meta.url))
const frontendDir = path.resolve(scriptDir, '..')
const repoDir = path.resolve(frontendDir, '..')
const outputPath = path.join(frontendDir, 'public', 'third_party', 'cargo', 'LICENSES.txt')

// The two crates that become WebAssembly. solver-core reaches the bundle only
// through them, and arrives on its own as a workspace member either way.
const SOLVER_MANIFESTS = ['sketch-solver/Cargo.toml', 'mate-solver/Cargo.toml']

// The workspace's own crates are Oversolved, not third-party software. They are
// covered by the repository's LICENSE.md and must not be listed as dependencies
// with someone else's terms.
const OWN_CRATES = new Set(['solver-core', 'sketch-solver', 'mate-solver'])

const LICENSE_FILE = /^(LICENSE|LICENCE|COPYING|NOTICE)([-.].*)?$/i

// Canonical texts published beside the bundle, for crates that declare a
// license without vendoring one. Read from disk so an entry can never name a
// text that is not actually there.
const spdxDir = path.join(frontendDir, 'public', 'third_party', 'spdx')
const SPDX_FALLBACKS = new Set(
  existsSync(spdxDir)
    ? readdirSync(spdxDir).filter(name => name.endsWith('.txt')).map(name => name.slice(0, -4))
    : [],
)

// The solvers' dependency graphs, resolved for the wasm target.
//
// --filter-platform drops what does not apply to wasm32, but it does not drop
// build-dependencies or proc macros: syn, quote and friends come back even
// though they only ever run on the machine doing the compiling. That is left
// alone deliberately. Separating them means reading cargo's resolve graph by
// dependency kind, and the failure mode of getting that wrong is a crate that
// ships with no notice. Listing a crate that owes nothing costs a paragraph.
function cargoPackages(manifest) {
  const raw = execFileSync('cargo', [
    'metadata',
    '--format-version', '1',
    '--manifest-path', manifest,
    '--filter-platform', 'wasm32-unknown-unknown',
  ], { cwd: repoDir, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 })
  return JSON.parse(raw).packages
}

// Crates vendor their license as one or more files beside Cargo.toml, and the
// dual-licensed ones ship both, so every match is kept rather than the first.
function licenseTexts(crateDir) {
  if (!existsSync(crateDir)) return []
  return readdirSync(crateDir)
    .filter(name => LICENSE_FILE.test(name))
    .sort()
    .map(name => ({ name, text: readFileSync(path.join(crateDir, name), 'utf8').trimEnd() }))
    .filter(entry => entry.text.length > 0)
}

function collect() {
  const found = new Map()

  for (const manifest of SOLVER_MANIFESTS) {
    for (const pkg of cargoPackages(manifest)) {
      if (OWN_CRATES.has(pkg.name)) continue
      const key = `${pkg.name}@${pkg.version}`
      if (found.has(key)) continue
      found.set(key, {
        name: pkg.name,
        version: pkg.version,
        license: pkg.license ?? null,
        repository: pkg.repository ?? null,
        texts: licenseTexts(path.dirname(pkg.manifest_path)),
      })
    }
  }

  return [...found.values()].sort((a, b) =>
    a.name.localeCompare(b.name, 'en') || a.version.localeCompare(b.version, 'en'))
}

function render(packages) {
  const withoutText = packages.filter(entry => entry.texts.length === 0)
  const lines = []

  lines.push('Third-party licenses: Rust crates in the solver WebAssembly')
  lines.push('')
  lines.push('This file is generated by scripts/generateRustNotices.mjs from the cargo')
  lines.push('dependency graphs of the sketch and mate solvers, which are compiled to')
  lines.push('WebAssembly and served from /wasm/. Each entry reproduces the license text')
  lines.push('the crate itself ships.')
  lines.push('')
  lines.push('It errs towards listing too much: the graph includes build-time crates such')
  lines.push('as syn and proc-macro2, which run on the machine doing the compiling and are')
  lines.push('not present in the WebAssembly. They are listed rather than filtered out,')
  lines.push('because listing a crate that owes nothing is harmless and the reverse is not.')
  lines.push('')
  lines.push('Two things are NOT here. Oversolved\'s own crates (solver-core, sketch-solver,')
  lines.push('mate-solver) are covered by the repository\'s LICENSE.md. The Rust standard')
  lines.push('library is linked into the WebAssembly but is not a package in any dependency')
  lines.push('graph, so cargo cannot report it; it is credited in ../toolchain/.')
  lines.push('')
  lines.push('Where a crate offers a choice of licenses, every text it ships is reproduced.')
  lines.push('Oversolved takes them under the permissive option, and the crate\'s own terms')
  lines.push('below are what governs.')
  lines.push('')
  lines.push(`Crates: ${packages.length}`)
  lines.push('')

  if (withoutText.length > 0) {
    lines.push('Crates that declare a license but vendor no text for it. Where a canonical')
    lines.push('copy of those terms is published beside this file, the entry names it.')
    lines.push('')
    for (const entry of withoutText) {
      lines.push(`  ${entry.name}@${entry.version}  ${entry.license ?? 'license not declared'}`)
    }
    lines.push('')
  }

  for (const entry of packages) {
    lines.push('='.repeat(78))
    lines.push('')
    lines.push(`${entry.name}@${entry.version}`)
    if (entry.license) lines.push(`License: ${entry.license}`)
    if (entry.repository) lines.push(`Source: ${entry.repository}`)
    lines.push('')
    if (entry.texts.length === 0) {
      lines.push('This crate vendors no license file of its own.')
      // Named rather than gestured at, so the test that checks every canonical
      // text is actually published has a filename to check.
      const canonical = (entry.license ?? '').split(/\s+(?:OR|AND)\s+/)
        .map(id => id.replace(/[()]/g, '').trim())
        .filter(id => SPDX_FALLBACKS.has(id))
      if (canonical.length > 0) {
        lines.push(`The terms are the standard text of ${canonical.join(' or ')}, in`)
        lines.push(canonical.map(id => `../spdx/${id}.txt`).join(' and ') + '.')
      }
      lines.push('')
      continue
    }
    for (const { name, text } of entry.texts) {
      lines.push(`--- ${name} ---`)
      lines.push('')
      lines.push(text)
      lines.push('')
    }
  }

  return lines.join('\n').trimEnd() + '\n'
}

function main() {
  const generated = render(collect())

  if (process.argv.includes('--check')) {
    const current = existsSync(outputPath) ? readFileSync(outputPath, 'utf8') : ''
    if (current === generated) {
      console.log(`rust notices are current (${outputPath})`)
      return
    }
    console.error('rust notices are stale. Run: npm run licenses:generate:rust')
    process.exitCode = 1
    return
  }

  mkdirSync(path.dirname(outputPath), { recursive: true })
  writeFileSync(outputPath, generated)
  console.log(`wrote ${outputPath}`)
}

main()
