/**
 * pack.ts parity + round-trip gate.
 *
 * 1. Re-pack the exact input Python packed (`__fixtures__/packFrame.json`,
 *    generated by `tests/wasm_harness/gen_pack_fixture.py`) and assert the
 *    binary section is byte-identical and the JSON header is structurally equal
 *    (not byte-equal: float formatting differs between json.dumps and
 *    JSON.stringify, which is irrelevant to the consumer).
 * 2. Round-trip the TS frame back through the real viewport decoder
 *    (`utils/geometryUnpack.ts`) and assert the bodies survive intact.
 */

import { describe, it, expect } from 'vitest'
import { packGeometryUpdate, type PackBody } from './pack'
import { unpackBodies, unpackPickBodies, type GeometryHeader } from '@/utils/geometryUnpack'
import fixture from './__fixtures__/packFrame.json'

interface ParsedFrame {
  paddedLen: number
  header: GeometryHeader & { request_id?: number }
  binary: Uint8Array
}

function parseFrame(frame: Uint8Array): ParsedFrame {
  const dv = new DataView(frame.buffer, frame.byteOffset, frame.byteLength)
  const paddedLen = dv.getUint32(0, false)
  const headerBytes = frame.subarray(4, 4 + paddedLen)
  // Trim trailing NUL padding before JSON.parse.
  let end = headerBytes.length
  while (end > 0 && headerBytes[end - 1] === 0) end--
  const header = JSON.parse(new TextDecoder().decode(headerBytes.subarray(0, end)))
  const binary = frame.subarray(4 + paddedLen)
  return { paddedLen, header, binary }
}

function hexToBytes(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2)
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16)
  return out
}

const input = fixture.input as unknown as {
  msgId: number
  bodies: Record<string, PackBody>
  pick_bodies: Record<string, PackBody>
  request_id: number
}

describe('packGeometryUpdate', () => {
  it('matches the Python reference frame (binary byte-exact, header structural)', () => {
    const tsFrame = packGeometryUpdate(input.msgId, input.bodies, {
      pickBodies: input.pick_bodies,
      requestId: input.request_id,
    })
    const py = parseFrame(hexToBytes(fixture.frameHex))
    const ts = parseFrame(tsFrame)

    // Binary section byte-for-byte identical (float32 verts + uint32 faces/tri2face).
    expect(Array.from(ts.binary)).toEqual(Array.from(py.binary))

    // Header structurally identical (offsets, counts, metadata, parsed floats).
    expect(ts.header).toEqual(py.header)
  })

  it('round-trips through the viewport decoder', () => {
    const tsFrame = packGeometryUpdate(input.msgId, input.bodies, {
      pickBodies: input.pick_bodies,
      requestId: input.request_id,
    })
    const { paddedLen, header } = parseFrame(tsFrame)
    // unpack* reads typed-array views from the frame's own buffer.
    const buffer = tsFrame.buffer as ArrayBuffer
    const bodies = unpackBodies(header, buffer, paddedLen)
    const pick = unpackPickBodies(header, buffer, paddedLen)

    expect(Object.keys(bodies)).toEqual(['body_a', 'body_b'])
    expect(Object.keys(pick)).toEqual(['pick_a'])

    const a = bodies.body_a
    expect(a.created_by).toBe('feat_extrude_1')
    expect(a.modified_by).toEqual(['feat_fillet_2'])
    expect(Array.from(a.mesh!.vertices as Float32Array)).toEqual([
      0, 0, 0, 10, 0, 0, 10, 10, 0, 0, 10, 0,
    ])
    expect(Array.from(a.mesh!.faces as Uint32Array)).toEqual([0, 1, 2, 0, 2, 3])
    expect(a.mesh!.triangle_to_face).toEqual([0, 0])
    expect(a.mesh!.face_data).toHaveLength(1)
    expect(a.mesh!.face_data![0].centroid).toEqual([5, 5, 0])
    expect(a.edges).toHaveLength(1)
    expect(a.vertex_queries).toEqual(['q:vert:0', 'q:vert:1'])

    // pick_a's tri2face references face index 3 (the GPU collision-id offset).
    expect(pick.pick_a.mesh!.triangle_to_face).toEqual([3])
  })

  it('packs an empty update to a valid header-only frame', () => {
    const frame = packGeometryUpdate(1, {})
    const { header, binary } = parseFrame(frame)
    expect(header.msgId).toBe(1)
    expect(header.bodies).toEqual({})
    expect(binary.byteLength).toBe(0)
  })
})
