import { describe, it, expect } from 'vitest'
import type { Mutation } from '@/types/cad'
import { mutationHandlers } from '@/hooks/usePartDoc'

const ALL_MUTATION_TYPES: Mutation['type'][] = [
  'move_vertex',
  'move_vertex_with_constraint',
  'move_entity',
  'add_constraint',
  'set_constraint_value',
  'set_constraint_pos',
  'delete',
  'add_entity',
  'add_entity_with_constraint',
  'add_projected_entity',
  'add_rect',
  'add_center_rect',
  'toggle_construction',
  'set_feature_plane',
  'add_sketch',
  'delete_feature',
  'set_feature_visibility',
  'add_plane',
  'set_plane_definition_field',
  'rename_feature',
  'toggle_sketch_plane_visibility',
  'toggle_plane_visibility',
  'add_extrude',
  'set_extrude_distance',
  'set_extrude_direction',
  'set_extrude_operation',
  'set_extrude_merge_target',
  'add_extrude_profile',
  'remove_extrude_profile',
  'add_revolve',
  'set_revolve_angle',
  'set_revolve_direction',
  'set_revolve_axis',
  'set_revolve_operation',
  'set_revolve_merge_target',
  'add_revolve_profile',
  'remove_revolve_profile',
  'add_import_step',
  'add_fillet',
  'add_chamfer',
  'set_fillet_radius',
  'set_chamfer_distance',
  'set_chamfer_angle',
  'set_chamfer_kind',
  'add_fillet_edge',
  'remove_fillet_edge',
  'add_chamfer_edge',
  'remove_chamfer_edge',
  'add_boolean',
  'set_boolean_operation',
  'set_boolean_target',
  'add_boolean_tool',
  'remove_boolean_tool',
  'set_boolean_keep_tools',
  'add_array',
  'set_array_mode',
  'set_array_source_body',
  'set_array_operation',
  'set_array_include_source',
  'set_array_count_x',
  'set_array_pitch_x',
  'set_array_direction_x_query',
  'set_array_count_y',
  'set_array_pitch_y',
  'set_array_direction_y_query',
  'set_array_count',
  'set_array_step_angle',
  'set_array_axis',
  'set_array_direction_x',
  'set_array_direction_y',
  'add_delete_body',
  'set_delete_body_target',
  'add_hole',
  'set_hole_sketch',
  'set_hole_diameter',
  'set_hole_depth',
  'set_hole_depth_mode',
  'set_hole_direction',
  'set_hole_target',
  'add_transform',
  'set_transform_field',
  'rename_part',
  'set_part_color',
  'set_part_transparency',
  'set_part_metalness',
  'mirror_entities',
  'add_mirror',
  'set_mirror_field',
  'reorder_features',
  'reorder_pick_field',
]

describe('mutationHandlers dispatch table', () => {
  it('covers every Mutation type variant', () => {
    expect(Object.keys(mutationHandlers).sort()).toEqual(ALL_MUTATION_TYPES.slice().sort())
  })

  it('returns undefined for unknown mutation type (dev guard would fire)', () => {
    const handlers = mutationHandlers as Record<string, unknown>
    expect(handlers['__unknown_type__']).toBeUndefined()
  })
})
