// Every undo/redo label the UI shows comes out of describeMutation's switch.
// The table below is the contract: one representative mutation per variant and
// the exact text it must render. Both maps are keyed by Mutation['type'], so a
// new variant makes this file fail to compile instead of silently rendering
// "unknown mutation" in the history tooltip.
import { describe, it, expect } from 'vitest'
import { describeMutation } from '@/utils/core/mutationDescriptions'
import type { Mutation } from '@/types/cad'

const pt: [number, number] = [0, 0]

const SAMPLES: { [K in Mutation['type']]: Extract<Mutation, { type: K }> } = {
  move_vertex: { type: 'move_vertex', featureId: 'sk1', entityId: 'e1', vertexKey: 'v1', to: pt },
  move_vertex_with_constraint: { type: 'move_vertex_with_constraint', featureId: 'sk1', entityId: 'e1', vertexKey: 'v1', to: pt, constraintKind: 'coincident' },
  move_entity: { type: 'move_entity', featureId: 'sk1', entityId: 'e1', delta: pt },
  resize_circle: { type: 'resize_circle', featureId: 'sk1', entityId: 'e1', radius: 5 },
  add_constraint: { type: 'add_constraint', featureId: 'sk1', kind: 'line', targets: ['a'] },
  set_constraint_value: { type: 'set_constraint_value', featureId: 'sk1', constraintId: 'c1', value: 3 },
  set_constraint_pos: { type: 'set_constraint_pos', featureId: 'sk1', constraintId: 'c1', pos: pt },
  set_constraint_sign: { type: 'set_constraint_sign', featureId: 'sk1', constraintId: 'c1', sign: -1 },
  delete: { type: 'delete', targets: ['a', 'b'] },
  add_entity: { type: 'add_entity', featureId: 'sk1', kind: 'line', params: [] },
  add_entity_with_constraint: { type: 'add_entity_with_constraint', featureId: 'sk1', kind: 'line', params: [], vertexKey: 'v1', constraintKind: 'coincident' },
  add_projected_entity: { type: 'add_projected_entity', featureId: 'sk1', kind: 'line', source: 'sk0' },
  add_rect: { type: 'add_rect', featureId: 'sk1', p0: pt, p1: pt },
  add_center_rect: { type: 'add_center_rect', featureId: 'sk1', center: pt, corner: pt },
  add_ngon: { type: 'add_ngon', featureId: 'sk1', center: pt, corner: pt, sides: 6 },
  apply_offset: { type: 'apply_offset', featureId: 'sk1', sourceIds: ['a', 'b'], distance: 10 },
  toggle_construction: { type: 'toggle_construction', targets: ['a', 'b'] },
  set_feature_plane: { type: 'set_feature_plane', featureId: 'sk1', plane: 'XY' },
  add_sketch: { type: 'add_sketch', featureId: 'sk1', label: 'Sketch 1' },
  delete_feature: { type: 'delete_feature', featureId: 'sk1' },
  set_feature_visibility: { type: 'set_feature_visibility', featureId: 'sk1', visible: false },
  add_plane: { type: 'add_plane', featureId: 'p1', label: 'Plane 1' },
  set_plane_definition_field: { type: 'set_plane_definition_field', featureId: 'p1', field: 'offset', value: 5 },
  rename_feature: { type: 'rename_feature', featureId: 'sk1', label: 'Sketch 1' },
  toggle_sketch_plane_visibility: { type: 'toggle_sketch_plane_visibility' },
  toggle_plane_visibility: { type: 'toggle_plane_visibility' },
  add_extrude: { type: 'add_extrude', featureId: 'ex1', label: 'Extrude 1', sketchQuery: 'q', distance: 5 },
  set_extrude_field: { type: 'set_extrude_field', featureId: 'ex1', field: 'distance', value: 3 },
  add_extrude_profile: { type: 'add_extrude_profile', featureId: 'ex1', sketchQuery: 'q' },
  remove_extrude_profile: { type: 'remove_extrude_profile', featureId: 'ex1', index: 2 },
  add_revolve: { type: 'add_revolve', featureId: 'rv1', label: 'Revolve 1', sketchQuery: 'q', angle: 90 },
  set_revolve_field: { type: 'set_revolve_field', featureId: 'rv1', field: 'angle', value: 3 },
  add_revolve_profile: { type: 'add_revolve_profile', featureId: 'rv1', sketchQuery: 'q' },
  remove_revolve_profile: { type: 'remove_revolve_profile', featureId: 'rv1', index: 2 },
  add_sweep: { type: 'add_sweep', featureId: 'sw1', label: 'Sweep 1', sketchQuery: 'q', pathQuery: 'pq' },
  set_sweep_field: { type: 'set_sweep_field', featureId: 'sw1', field: 'sketch', value: 3 },
  add_sweep_profile: { type: 'add_sweep_profile', featureId: 'sw1', sketchQuery: 'q' },
  remove_sweep_profile: { type: 'remove_sweep_profile', featureId: 'sw1', index: 2 },
  add_sweep_path: { type: 'add_sweep_path', featureId: 'sw1', pathQuery: 'pq' },
  remove_sweep_path: { type: 'remove_sweep_path', featureId: 'sw1', index: 2 },
  add_import_step: { type: 'add_import_step', featureId: 'im1', fileId: 'f1', label: 'Model' },
  add_fillet: { type: 'add_fillet', featureId: 'fi1', label: 'Fillet 1' },
  add_chamfer: { type: 'add_chamfer', featureId: 'ch1', label: 'Chamfer 1' },
  set_fillet_field: { type: 'set_fillet_field', featureId: 'fi1', field: 'radius', value: 3 },
  set_chamfer_field: { type: 'set_chamfer_field', featureId: 'ch1', field: 'distance', value: 3 },
  add_fillet_edge: { type: 'add_fillet_edge', featureId: 'fi1', edgeQuery: 'eq' },
  remove_fillet_edge: { type: 'remove_fillet_edge', featureId: 'fi1', index: 2 },
  add_chamfer_edge: { type: 'add_chamfer_edge', featureId: 'ch1', edgeQuery: 'eq' },
  remove_chamfer_edge: { type: 'remove_chamfer_edge', featureId: 'ch1', index: 2 },
  add_boolean: { type: 'add_boolean', featureId: 'bo1', label: 'Boolean 1' },
  set_boolean_field: { type: 'set_boolean_field', featureId: 'bo1', field: 'operation', value: 3 },
  add_boolean_tool: { type: 'add_boolean_tool', featureId: 'bo1', tool: 't1' },
  remove_boolean_tool: { type: 'remove_boolean_tool', featureId: 'bo1', tool: 't1' },
  add_array: { type: 'add_array', featureId: 'ar1', label: 'Array 1' },
  set_array_field: { type: 'set_array_field', featureId: 'ar1', field: 'mode', value: 3 },
  add_circular_array: { type: 'add_circular_array', featureId: 'ca1', label: 'Circular Array 1' },
  set_circular_array_field: { type: 'set_circular_array_field', featureId: 'ca1', field: 'count', value: 3 },
  add_delete_body: { type: 'add_delete_body', featureId: 'db1', label: 'Delete Body' },
  add_delete_body_ref: { type: 'add_delete_body_ref', featureId: 'db1', bodyQuery: 'bq' },
  remove_delete_body_ref: { type: 'remove_delete_body_ref', featureId: 'db1', index: 2 },
  add_hole: { type: 'add_hole', featureId: 'ho1', label: 'Hole 1' },
  set_hole_field: { type: 'set_hole_field', featureId: 'ho1', field: 'diameter', value: 3 },
  add_transform: { type: 'add_transform', featureId: 'tr1', label: 'Transform 1' },
  set_transform_field: { type: 'set_transform_field', featureId: 'tr1', field: 'bodies', value: 3 },
  add_transform_body: { type: 'add_transform_body', featureId: 'tr1', bodyQuery: 'bq' },
  remove_transform_body: { type: 'remove_transform_body', featureId: 'tr1', index: 2 },
  rename_part: { type: 'rename_part', bodyId: 'b1', name: 'Body' },
  set_part_color: { type: 'set_part_color', bodyId: 'b1', color: '#fff' },
  set_part_transparency: { type: 'set_part_transparency', bodyId: 'b1', transparency: 0.5 },
  set_part_metalness: { type: 'set_part_metalness', bodyId: 'b1', metalness: 0.2 },
  set_part_roughness: { type: 'set_part_roughness', bodyId: 'b1', roughness: 0.3 },
  set_part_transmission: { type: 'set_part_transmission', bodyId: 'b1', transmission: 0.4 },
  add_mirror: { type: 'add_mirror', featureId: 'mi1', label: 'Mirror 1' },
  set_mirror_field: { type: 'set_mirror_field', featureId: 'mi1', field: 'body', value: 3 },
  add_variable: { type: 'add_variable', featureId: 'va1', label: 'Variable 1' },
  set_variable_field: { type: 'set_variable_field', featureId: 'va1', field: 'expression', value: 3 },
  reorder_features: { type: 'reorder_features', featureId: 'sk1', toIndex: 5 },
  set_body_visibility: { type: 'set_body_visibility', bodyId: 'b1', visible: false },
  reorder_pick_field: { type: 'reorder_pick_field', featureId: 'sk1', field: 'sketch', fromIndex: 0, toIndex: 5 },
  set_feature_suppression: { type: 'set_feature_suppression', featureId: 'sk1', suppressed: true },
  set_rollback: { type: 'set_rollback', position: 3 },
  edit_session: { type: 'edit_session', featureId: 'sk1' },
  preview_commit: { type: 'preview_commit', description: 'change sketch' },
  remove_dangling_content: { type: 'remove_dangling_content', features: { sk1: { entities: [], constraints: [] } } },
}

const EXPECTED: Record<Mutation['type'], string> = {
  move_vertex: 'move vertex v1 on e1 in sk1',
  move_vertex_with_constraint: 'snap vertex v1 on e1 with coincident constraint',
  move_entity: 'move e1 in sk1',
  resize_circle: 'resize e1 in sk1',
  add_constraint: 'add line constraint in sk1',
  set_constraint_value: 'set c1 value in sk1',
  set_constraint_pos: 'set c1 pos in sk1',
  set_constraint_sign: 'flip c1 side in sk1',
  delete: 'delete 2 element(s)',
  add_entity: 'add line in sk1',
  add_entity_with_constraint: 'add line with coincident constraint in sk1',
  add_projected_entity: 'add line from sk0 in sk1',
  add_rect: 'add rect in sk1',
  add_center_rect: 'add center rect in sk1',
  add_ngon: 'add 6-gon in sk1',
  apply_offset: 'offset 2 entity(ies) by 10 in sk1',
  toggle_construction: 'toggle construction on 2 element(s)',
  set_feature_plane: 'set plane of sk1 to XY',
  add_sketch: 'add Sketch 1',
  delete_feature: 'delete feature sk1',
  set_feature_visibility: 'hide sk1',
  add_plane: 'add Plane 1',
  set_plane_definition_field: 'edit plane p1: offset',
  rename_feature: 'rename sk1 to Sketch 1',
  toggle_sketch_plane_visibility: 'toggle sketch/plane visibility',
  toggle_plane_visibility: 'toggle plane visibility',
  add_extrude: 'add extrude Extrude 1',
  set_extrude_field: 'set extrude distance to 3',
  add_extrude_profile: 'add extrude profile q',
  remove_extrude_profile: 'remove extrude profile at index 2',
  add_revolve: 'add revolve Revolve 1',
  set_revolve_field: 'set revolve angle to 3',
  add_revolve_profile: 'add revolve profile q',
  remove_revolve_profile: 'remove revolve profile at index 2',
  add_sweep: 'add sweep Sweep 1',
  set_sweep_field: 'set sweep sketch to 3',
  add_sweep_profile: 'add sweep profile q',
  remove_sweep_profile: 'remove sweep profile at index 2',
  add_sweep_path: 'add sweep path pq',
  remove_sweep_path: 'remove sweep path at index 2',
  add_import_step: 'import STEP Model',
  add_fillet: 'add fillet Fillet 1',
  add_chamfer: 'add chamfer Chamfer 1',
  set_fillet_field: 'set fillet radius to 3',
  set_chamfer_field: 'set chamfer distance to 3',
  add_fillet_edge: 'add fillet edge eq',
  remove_fillet_edge: 'remove fillet edge at index 2',
  add_chamfer_edge: 'add chamfer edge eq',
  remove_chamfer_edge: 'remove chamfer edge at index 2',
  add_boolean: 'add boolean Boolean 1',
  set_boolean_field: 'set boolean operation to 3',
  add_boolean_tool: 'add boolean tool t1',
  remove_boolean_tool: 'remove boolean tool t1',
  add_array: 'add array Array 1',
  set_array_field: 'set array mode to 3',
  add_circular_array: 'add circular array Circular Array 1',
  set_circular_array_field: 'set circular array count to 3',
  add_delete_body: 'add delete body Delete Body',
  add_delete_body_ref: 'add delete body ref bq',
  remove_delete_body_ref: 'remove delete body ref at index 2',
  add_hole: 'add hole Hole 1',
  set_hole_field: 'set hole diameter to 3',
  add_transform: 'add transform Transform 1',
  set_transform_field: 'set transform bodies to 3',
  add_transform_body: 'add transform body bq',
  remove_transform_body: 'remove transform body at index 2',
  rename_part: 'rename b1 to Body',
  set_part_color: 'set b1 color to #fff',
  set_part_transparency: 'set b1 transparency to 0.5',
  set_part_metalness: 'set b1 metalness to 0.2',
  set_part_roughness: 'set b1 roughness to 0.3',
  set_part_transmission: 'set b1 transmission to 0.4',
  add_mirror: 'add mirror Mirror 1',
  set_mirror_field: 'set mirror body to 3',
  add_variable: 'add variable Variable 1',
  set_variable_field: 'set variable expression to 3',
  reorder_features: 'reorder sk1 to index 5',
  set_body_visibility: 'hide body b1',
  reorder_pick_field: 'reorder pick field sketch in sk1',
  set_feature_suppression: 'suppress sk1',
  set_rollback: 'move rollback to 3',
  edit_session: 'edit sk1',
  preview_commit: 'change sketch',
  remove_dangling_content: 'remove dangling projections / superfluous constraints',
}

describe('describeMutation', () => {
  it.each(Object.keys(EXPECTED) as Mutation['type'][])('renders the %s label', (type) => {
    expect(describeMutation(SAMPLES[type])).toBe(EXPECTED[type])
  })

  it('renders the two optional rollback and edit-session forms', () => {
    expect(describeMutation({ type: 'set_rollback', position: null })).toBe('move rollback to end')
    expect(describeMutation({ type: 'edit_session', featureId: '' })).toBe('edit feature')
  })

  it('falls back to a single unknown label for an unrecognized type', () => {
    expect(describeMutation({ type: 'not_a_mutation' } as unknown as Mutation)).toBe('unknown mutation')
  })
})
