import importlib
import pytest

pytestmark = [
    pytest.mark.skipif(
        not importlib.util.find_spec("cadquery"), reason="cadquery not installed"
    ),
    pytest.mark.skipif(
        not importlib.util.find_spec("vtkmodules"), reason="vtkmodules not installed"
    ),
]


#  ── Fillet tests ──


def test_fillet_single_edge():
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec, assert_mesh_valid

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    spec["features"].append({
        "id": "fillet1",
        "kind": "fillet",
        "label": "Fillet",
        "edges": ["?body_ex1:edge:0"],
        "radius": 1.0,
    })
    r = build(spec)
    assert r["result"]["fillet1"]["status"] == "ok", f"build failed: {r['result']['fillet1'].get('exception')}"
    mesh = r["bodies"]["body_ex1"]["mesh"]
    assert_mesh_valid(mesh)


def test_fillet_multiple_edges():
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec, assert_mesh_valid

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    spec["features"].append({
        "id": "fillet1",
        "kind": "fillet",
        "label": "Fillet",
        "edges": ["?body_ex1:edge:0", "?body_ex1:edge:1"],
        "radius": 1.0,
    })
    r = build(spec)
    assert r["result"]["fillet1"]["status"] == "ok"
    mesh = r["bodies"]["body_ex1"]["mesh"]
    assert_mesh_valid(mesh)


def test_fillet_zero_radius_errors():
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    spec["features"].append({
        "id": "fillet1",
        "kind": "fillet",
        "label": "Fillet",
        "edges": ["?body_ex1:edge:0"],
        "radius": 0,
    })
    r = build(spec)
    assert r["result"]["fillet1"]["status"] == "exception"
    assert "radius must be positive" in r["result"]["fillet1"].get("exception", "")


def test_fillet_negative_radius_errors():
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    spec["features"].append({
        "id": "fillet1",
        "kind": "fillet",
        "label": "Fillet",
        "edges": ["?body_ex1:edge:0"],
        "radius": -1,
    })
    r = build(spec)
    assert r["result"]["fillet1"]["status"] == "exception"
    assert "radius must be positive" in r["result"]["fillet1"].get("exception", "")


def test_fillet_empty_edges_errors():
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    spec["features"].append({
        "id": "fillet1",
        "kind": "fillet",
        "label": "Fillet",
        "edges": [],
        "radius": 1.0,
    })
    r = build(spec)
    assert r["result"]["fillet1"]["status"] == "exception"
    assert "requires at least one edge" in r["result"]["fillet1"].get("exception", "")


def test_fillet_3id_ancestry_query():
    """Fillet edge queries stored in '3-ID' format (body_id + created_by + body_id)
    must resolve correctly. This is the format generated by solid_to_edges(body_id=...).
    """
    from oversolved.kernel.builder import build
    from oversolved.kernel.query import make_ancestry_query
    from solver_helpers import full_rect_extrude_spec, assert_mesh_valid

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    q3 = make_ancestry_query(
        ["@body_ex1edge0", "@ex1", "@body_ex1"], "straightedge"
    )
    spec["features"].append({
        "id": "fillet1",
        "kind": "fillet",
        "label": "Fillet",
        "edges": [q3],
        "radius": 1.0,
    })
    r = build(spec)
    assert r["result"]["fillet1"]["status"] == "ok", \
        f"3-ID ancestry query failed: {r['result']['fillet1'].get('exception')}"
    mesh = r["bodies"]["body_ex1"]["mesh"]
    assert_mesh_valid(mesh)


def test_fillet_roundtrip_via_edge_queries():
    """Simulate the real frontend round-trip: edge_queries from build output
    are fed back as fillet edge input. This verifies that queries generated
    by solid_to_edges(body_id=...) can be consumed by _resolve_fillet_edges().
    """
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec, assert_mesh_valid

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    r0 = build(spec)
    edge_queries = r0["bodies"]["body_ex1"].get("edge_queries", [])
    assert len(edge_queries) > 0, "no edge_queries in build output"

    spec["features"].append({
        "id": "fillet1",
        "kind": "fillet",
        "label": "Fillet",
        "edges": [edge_queries[0]],
        "radius": 1.0,
    })
    r = build(spec)
    assert r["result"]["fillet1"]["status"] == "ok", \
        f"round-trip fillet failed with query {edge_queries[0]!r}: {r['result']['fillet1'].get('exception')}"
    mesh = r["bodies"]["body_ex1"]["mesh"]
    assert_mesh_valid(mesh)


def test_fillet_chain_after_extrude():
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec, assert_mesh_valid

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    spec["features"].append({
        "id": "fillet1",
        "kind": "fillet",
        "label": "Fillet",
        "edges": ["?body_ex1:edge:0"],
        "radius": 1.0,
    })
    r = build(spec)
    assert r["result"]["fillet1"]["status"] == "ok"
    mesh = r["bodies"]["body_ex1"]["mesh"]
    assert_mesh_valid(mesh)


def test_fillet_updates_body():
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    r_before = build(spec)
    verts_before = r_before["bodies"]["body_ex1"]["mesh"]["vertices"]

    spec["features"].append({
        "id": "fillet1",
        "kind": "fillet",
        "label": "Fillet",
        "edges": ["?body_ex1:edge:0"],
        "radius": 2.0,
    })
    r_after = build(spec)
    verts_after = r_after["bodies"]["body_ex1"]["mesh"]["vertices"]

    assert len(verts_after) > len(verts_before)


#  ── Chamfer tests  ──


def test_chamfer_single_edge():
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec, assert_mesh_valid

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    spec["features"].append({
        "id": "chamfer1",
        "kind": "chamfer",
        "label": "Chamfer",
        "edges": ["?body_ex1:edge:0"],
        "distance": 1.0,
    })
    r = build(spec)
    assert r["result"]["chamfer1"]["status"] == "ok"
    mesh = r["bodies"]["body_ex1"]["mesh"]
    assert_mesh_valid(mesh)


def test_chamfer_multiple_edges():
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec, assert_mesh_valid

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    spec["features"].append({
        "id": "chamfer1",
        "kind": "chamfer",
        "label": "Chamfer",
        "edges": ["?body_ex1:edge:0", "?body_ex1:edge:1"],
        "distance": 1.0,
    })
    r = build(spec)
    assert r["result"]["chamfer1"]["status"] == "ok"
    mesh = r["bodies"]["body_ex1"]["mesh"]
    assert_mesh_valid(mesh)


def test_chamfer_distance_zero_errors():
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    spec["features"].append({
        "id": "chamfer1",
        "kind": "chamfer",
        "label": "Chamfer",
        "edges": ["?body_ex1:edge:0"],
        "distance": 0,
    })
    r = build(spec)
    assert r["result"]["chamfer1"]["status"] == "exception"
    assert "distance must be positive" in r["result"]["chamfer1"].get("exception", "")


def test_chamfer_negative_distance_errors():
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    spec["features"].append({
        "id": "chamfer1",
        "kind": "chamfer",
        "label": "Chamfer",
        "edges": ["?body_ex1:edge:0"],
        "distance": -1,
    })
    r = build(spec)
    assert r["result"]["chamfer1"]["status"] == "exception"
    assert "distance must be positive" in r["result"]["chamfer1"].get("exception", "")


def test_chamfer_empty_edges_errors():
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    spec["features"].append({
        "id": "chamfer1",
        "kind": "chamfer",
        "label": "Chamfer",
        "edges": [],
        "distance": 1.0,
    })
    r = build(spec)
    assert r["result"]["chamfer1"]["status"] == "exception"
    assert "requires at least one edge" in r["result"]["chamfer1"].get("exception", "")


def test_chamfer_chain_after_extrude():
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec, assert_mesh_valid

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    spec["features"].append({
        "id": "chamfer1",
        "kind": "chamfer",
        "label": "Chamfer",
        "edges": ["?body_ex1:edge:0"],
        "distance": 1.0,
    })
    r = build(spec)
    assert r["result"]["chamfer1"]["status"] == "ok"
    mesh = r["bodies"]["body_ex1"]["mesh"]
    assert_mesh_valid(mesh)


def test_chamfer_updates_body():
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    r_before = build(spec)
    verts_before = r_before["bodies"]["body_ex1"]["mesh"]["vertices"]

    spec["features"].append({
        "id": "chamfer1",
        "kind": "chamfer",
        "label": "Chamfer",
        "edges": ["?body_ex1:edge:0"],
        "distance": 2.0,
    })
    r_after = build(spec)
    verts_after = r_after["bodies"]["body_ex1"]["mesh"]["vertices"]

    assert len(verts_after) > len(verts_before)


#  ── Chain tests ──


def test_fillet_then_chamfer():
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec, assert_mesh_valid

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    spec["features"].append({
        "id": "fillet1",
        "kind": "fillet",
        "label": "Fillet",
        "edges": ["?body_ex1:edge:0"],
        "radius": 1.0,
    })
    spec["features"].append({
        "id": "chamfer1",
        "kind": "chamfer",
        "label": "Chamfer",
        "edges": ["?body_ex1:edge:1"],
        "distance": 0.5,
    })
    r = build(spec)
    assert r["result"]["fillet1"]["status"] == "ok"
    assert r["result"]["chamfer1"]["status"] == "ok"
    mesh = r["bodies"]["body_ex1"]["mesh"]
    assert_mesh_valid(mesh)


def test_fillet_respects_edge_list():
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec

    spec1 = full_rect_extrude_spec(w=10, h=10, d=5)
    spec1["features"].append({
        "id": "fillet1",
        "kind": "fillet",
        "label": "Fillet",
        "edges": ["?body_ex1:edge:0"],
        "radius": 1.0,
    })
    r1 = build(spec1)
    verts1 = len(r1["bodies"]["body_ex1"]["mesh"]["vertices"])

    spec_all = full_rect_extrude_spec(w=10, h=10, d=5)
    spec_all["features"].append({
        "id": "fillet1",
        "kind": "fillet",
        "label": "Fillet",
        "edges": [f"?body_ex1:edge:{i}" for i in range(12)],
        "radius": 1.0,
    })
    r_all = build(spec_all)
    verts_all = len(r_all["bodies"]["body_ex1"]["mesh"]["vertices"])

    assert verts1 < verts_all, (
        f"single-edge fillet ({verts1}) should have fewer verts than all-edge fillet ({verts_all})"
    )


def test_fillet_body_modified_between_roundtrips():
    """Fillet using a 3-ID ancestry query that was generated before a
    body-modifying operation (e.g., another fillet) must still resolve.

    This simulates the scenario from bugreports/server_crash_20260509_215800.md
    where the fillet edge query was stored before a body-mutating operation.
    """
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    r0 = build(spec)
    edge_queries = r0["bodies"]["body_ex1"].get("edge_queries", [])
    assert len(edge_queries) > 0

    # Simulate a prior body-modifying operation (another fillet)
    spec["features"].append({
        "id": "fillet1",
        "kind": "fillet",
        "label": "Fillet 1",
        "edges": ["?body_ex1:edge:0"],
        "radius": 1.0,
    })
    # Use hash-based query from before the first fillet modified the body
    spec["features"].append({
        "id": "fillet2",
        "kind": "fillet",
        "label": "Fillet 2",
        "edges": [edge_queries[1]],
        "radius": 1.0,
    })
    r = build(spec)
    # fillet1 modifies the body shape; fillet2 should handle gracefully
    assert r["result"]["fillet2"]["status"] in ("ok", "exception"), \
        f"unexpected status: {r['result']['fillet2']}"


def test_multiple_fillet_features():
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec, assert_mesh_valid

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    spec["features"].append({
        "id": "fillet1",
        "kind": "fillet",
        "label": "Fillet 1",
        "edges": ["?body_ex1:edge:0"],
        "radius": 1.0,
    })
    spec["features"].append({
        "id": "fillet2",
        "kind": "fillet",
        "label": "Fillet 2",
        "edges": ["?body_ex1:edge:1"],
        "radius": 0.5,
    })
    r = build(spec)
    assert r["result"]["fillet1"]["status"] == "ok"
    assert r["result"]["fillet2"]["status"] == "ok"
    mesh = r["bodies"]["body_ex1"]["mesh"]
    assert_mesh_valid(mesh)


#  ── Face query as fillet edge (regression: gface queries from UI) ──


def test_fillet_resolves_face_query_on_cylinder():
    """Fillet edge given as a gface_ query (face reference) must resolve all
    edges of that face and fillet them.

    This simulates the scenario from bugreports/filled_from_face_1_20260520_192546.md
    and filled_from_face_2_20260520_192600.md where the UI stored a face query
    instead of an edge query in the fillet feature.
    """
    from oversolved.kernel.builder import build
    from solver_helpers import assert_mesh_valid

    # Cylinder: circle r=10 extrude d=10 on Top plane (matches bugreport geometry)
    spec = {
        "features": [
            {
                "id": "sk1",
                "kind": "sketch",
                "plane": "Top",
                "entities": [{"id": "c1", "kind": "circle"}],
                "initial": {"c1": [0, 0, 10]},
                "constraints": [
                    {"id": "co1", "kind": "coincident",
                     "a": "$sk1/c1center", "b": "@builtin_origin"},
                    {"id": "d1", "kind": "diameter", "target": "$sk1/c1", "value": 20},
                ],
            },
            {
                "id": "ex1",
                "kind": "extrude",
                "sketch": "$sk1",
                "distance": 10,
                "direction": "normal",
            },
        ]
    }
    r0 = build(spec)
    assert r0["result"]["ex1"]["status"] == "ok", r0["result"]["ex1"]
    face_queries = r0["bodies"]["body_ex1"]["mesh"].get("face_queries", [])
    assert len(face_queries) > 0, "build should produce face_queries"

    spec["features"].append({
        "id": "fillet1",
        "kind": "fillet",
        "label": "Fillet",
        "edges": [face_queries[0]],
        "radius": 1.0,
    })
    r = build(spec)
    assert r["result"]["fillet1"]["status"] == "ok", (
        f"fillet with face query failed: {r['result']['fillet1'].get('exception')}"
    )
    assert_mesh_valid(r["bodies"]["body_ex1"]["mesh"])


def test_fillet_resolves_second_face_query_on_cylinder():
    """Same as test_fillet_resolves_face_query_on_cylinder but uses a different
    face (e.g. the other flat face of the cylinder).

    Covers the second scenario from the bugreports where a different face hash
    was used.
    """
    from oversolved.kernel.builder import build
    from solver_helpers import assert_mesh_valid

    spec = {
        "features": [
            {
                "id": "sk1",
                "kind": "sketch",
                "plane": "Top",
                "entities": [{"id": "c1", "kind": "circle"}],
                "initial": {"c1": [0, 0, 10]},
                "constraints": [
                    {"id": "co1", "kind": "coincident",
                     "a": "$sk1/c1center", "b": "@builtin_origin"},
                    {"id": "d1", "kind": "diameter", "target": "$sk1/c1", "value": 20},
                ],
            },
            {
                "id": "ex1",
                "kind": "extrude",
                "sketch": "$sk1",
                "distance": 10,
                "direction": "normal",
            },
        ]
    }
    r0 = build(spec)
    assert r0["result"]["ex1"]["status"] == "ok", r0["result"]["ex1"]
    face_queries = r0["bodies"]["body_ex1"]["mesh"].get("face_queries", [])
    assert len(face_queries) >= 2, "cylinder should have at least 2 flat faces"

    spec["features"].append({
        "id": "fillet1",
        "kind": "fillet",
        "label": "Fillet",
        "edges": [face_queries[1]],
        "radius": 1.0,
    })
    r = build(spec)
    assert r["result"]["fillet1"]["status"] == "ok", (
        f"fillet with second face query failed: {r['result']['fillet1'].get('exception')}"
    )
    assert_mesh_valid(r["bodies"]["body_ex1"]["mesh"])


# ─── fix-143: _solve_transform module ownership ───

def test_solve_transform_not_in_fillet_module():
    """_solve_transform must not be defined in the fillet/chamfer module."""
    import oversolved.kernel.solver_features_fillet_chamfer as fc_mod
    assert not hasattr(fc_mod, "_solve_transform"), (
        "_solve_transform should only live in solver_features_transform_mirror"
    )


def test_solve_transform_resolves_from_correct_module():
    """_solve_transform must be defined in solver_features_transform_mirror."""
    import oversolved.kernel.solver_features_transform_mirror as tm
    assert hasattr(tm, "_solve_transform")


# ─── fix-144: chamfer kind shadowed by feature kind ───

def test_chamfer_distance_mode_unchanged():
    """Default distance chamfer still works after the kind-shadow fix."""
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec, assert_mesh_valid

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    spec["features"].append({
        "id": "ch1",
        "kind": "chamfer",
        "label": "Chamfer",
        "edges": ["?body_ex1:edge:0"],
        "chamfer": {"distance": 1.0, "kind": "distance"},
    })
    r = build(spec)
    assert r["result"]["ch1"]["status"] == "ok", r["result"]["ch1"].get("exception")
    assert_mesh_valid(r["bodies"]["body_ex1"]["mesh"])


def test_chamfer_angle_distance_mode():
    """Chamfer with kind=angle_distance in the sub-dict must not fall back to distance mode."""
    import unittest.mock as mock
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    spec["features"].append({
        "id": "ch1",
        "kind": "chamfer",
        "label": "Chamfer",
        "edges": ["?body_ex1:edge:0"],
        "chamfer": {"distance": 1.0, "angle": 30.0, "kind": "angle_distance"},
    })

    with mock.patch("oversolved.kernel.solver_features_fillet_chamfer.apply_chamfer", wraps=__import__(
        "oversolved.kernel.solver_features_fillet_chamfer", fromlist=["apply_chamfer"]
    ).apply_chamfer) as mock_chamfer:
        r = build(spec)

    assert r["result"]["ch1"]["status"] == "ok", r["result"]["ch1"].get("exception")
    assert mock_chamfer.called
    _, kwargs = mock_chamfer.call_args
    assert kwargs.get("kind") == "angle_distance", (
        f"apply_chamfer was called with kind={kwargs.get('kind')!r}, expected 'angle_distance'"
    )


def test_fillet_duplicate_edge_and_face_query():
    """Fillet with both an edge query AND a face query that resolve to
    the same OCC edge must not produce duplicate geometry.

    When _resolve_fillet_edges returns the same edge twice (once from the
    edge query, once from the face query), BRepFilletAPI_MakeFillet applies
    the fillet twice on the same edge, creating duplicate faces/edges with
    identical geometry hashes. The dedup fix in _resolve_fillet_edges
    prevents this.
    """
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec, assert_mesh_valid

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    r0 = build(spec)
    assert r0["result"]["ex1"]["status"] == "ok"

    body = r0["bodies"]["body_ex1"]
    edge_q = body.get("edge_queries", [])
    face_q = body.get("mesh", {}).get("face_queries", [])

    # Build a fillet with BOTH an edge query AND a face query
    # Pick edge 0 and the face at index 0 whose face-edge is edge 0
    spec["features"].append({
        "id": "fillet1",
        "kind": "fillet",
        "label": "Fillet",
        "edges": [edge_q[0], face_q[0]],
        "radius": 1.0,
    })
    r = build(spec)
    assert r["result"]["fillet1"]["status"] == "ok", (
        f"fillet with edge+face query failed: {r['result']['fillet1'].get('exception')}"
    )

    body_final = r["bodies"]["body_ex1"]
    mesh = body_final["mesh"]
    final_fq = mesh.get("face_queries", [])
    final_eq = body_final.get("edge_queries", [])
    assert len(final_fq) == len(set(final_fq)), (
        f"Duplicate face queries after fillet: {len(final_fq)} faces, "
        f"{len(final_fq) - len(set(final_fq))} duplicates"
    )
    assert len(final_eq) == len(set(final_eq)), (
        f"Duplicate edge queries after fillet: {len(final_eq)} edges, "
        f"{len(final_eq) - len(set(final_eq))} duplicates"
    )
    assert_mesh_valid(mesh)


def _circle_extrude_spec(radius: float = 10.0, distance: float = 10.0) -> dict:
    """Spec: a single circle sketch on the top plane extruded into a cylinder."""
    sketch = {
        "id": "sk_cyl",
        "kind": "sketch",
        "label": "circle",
        "plane": "@builtin_plane_top",
        "entities": [{"id": "circ", "kind": "circle"}],
        "initial": {"circ": [0, 0, radius]},
        "constraints": [
            {"id": "cc", "kind": "coincident",
             "a": "$circcenter", "b": "@builtin_origin"},
            {"id": "cd", "kind": "diameter",
             "target": "$circ", "value": 2 * radius, "pos": [0, 0]},
        ],
    }
    extrude = {
        "id": "ex_cyl",
        "kind": "extrude",
        "label": "extrude",
        "sketch": "$sk_cyl",
        "distance": distance,
        "direction": "normal",
    }
    return {"features": [sketch, extrude]}


def test_fillet_cylinder_edge_queries_unique():
    """Regression: filleting a cylinder's circular edge must yield unique
    edge queries.

    OCC represents each circular B-rep edge as two semicircle arcs with the
    same center/radius and an identical [0, pi] span, differing only in
    x_axis direction. The edge geometry hash previously ignored orientation,
    so the two halves produced identical edge queries -- the frontend then
    allocated one selection id for two distinct edges, breaking picking
    ("Two edges share the same query string"). The arc hash now includes
    axis/x_axis so the halves stay distinct.
    """
    from oversolved.kernel.builder import build

    spec = _circle_extrude_spec(radius=10.0, distance=10.0)
    r0 = build(spec)
    assert r0["result"]["ex_cyl"]["status"] == "ok", (
        f"cylinder build failed: {r0['result']['ex_cyl'].get('exception')}"
    )

    body = r0["bodies"]["body_ex_cyl"]
    face_q = body.get("mesh", {}).get("face_queries", [])
    # Fillet the circular rim by selecting a flat (top/bottom) face, mirroring
    # the user-reported document. This rounds the circular edge and forces OCC
    # to emit the split-arc geometry that triggered the collision.
    flat = [q for q in face_q if "flatface" in q] or face_q
    assert flat, "cylinder produced no face queries"

    spec["features"].append({
        "id": "fillet_cyl",
        "kind": "fillet",
        "label": "Fillet",
        "edges": [flat[0]],
        "radius": 1.0,
    })
    r = build(spec)
    assert r["result"]["fillet_cyl"]["status"] == "ok", (
        f"fillet failed: {r['result']['fillet_cyl'].get('exception')}"
    )

    final_eq = r["bodies"]["body_ex_cyl"].get("edge_queries", [])
    dup = len(final_eq) - len(set(final_eq))
    assert dup == 0, (
        f"Duplicate edge queries after filleting cylinder: {dup} duplicate(s) "
        f"out of {len(final_eq)} edges"
    )


def _rim_radius_edges(edges, rim_y, radius=10.0, tol=1e-6):
    """Full-radius circular edges sitting at a given rim height (axis = Y)."""
    return [
        ed for ed in edges
        if ed.get("center")
        and abs(ed["center"][1] - rim_y) < tol
        and abs(ed.get("radius", 0.0) - radius) < tol
    ]


def test_fillet_targets_the_picked_rim_not_the_opposite_one():
    """Regression for 'wrong edge gets the fillet'.

    A cylinder (axis = Y) has two circular rims: bottom at y=0, top at
    y=distance. Selecting the TOP rim's edge query and filleting it must
    round the TOP rim and leave the bottom rim sharp. The reported bug rounds
    the opposite rim because the resolver ignores the query's geometry hash
    and picks the first OCC edge instead.
    """
    from oversolved.kernel.builder import build

    distance = 10.0
    spec = _circle_extrude_spec(radius=10.0, distance=distance)
    r0 = build(spec)
    assert r0["result"]["ex_cyl"]["status"] == "ok"

    body = r0["bodies"]["body_ex_cyl"]
    edges = body["edges"]
    queries = body["edge_queries"]

    top_q = next(
        q for ed, q in zip(edges, queries)
        if ed.get("center")
        and abs(ed["center"][1] - distance) < 1e-6
        and abs(ed.get("radius", 0.0) - 10.0) < 1e-6
    )

    spec["features"].append({
        "id": "fillet_cyl",
        "kind": "fillet",
        "label": "Fillet",
        "edges": [top_q],
        "radius": 1.0,
    })
    r = build(spec)
    assert r["result"]["fillet_cyl"]["status"] == "ok", (
        f"fillet failed: {r['result']['fillet_cyl'].get('exception')}"
    )

    final_edges = r["bodies"]["body_ex_cyl"]["edges"]
    top_sharp = _rim_radius_edges(final_edges, rim_y=distance)
    bottom_sharp = _rim_radius_edges(final_edges, rim_y=0.0)

    assert not top_sharp, (
        "picked TOP rim should have been filleted, but a sharp radius-10 edge "
        "still sits at y=distance -- the fillet landed on the wrong rim"
    )
    assert bottom_sharp, "bottom rim should stay sharp (unfilleted)"


def _two_circle_extrude_spec() -> dict:
    """Two disjoint circles in one sketch extruded into two separate bodies."""
    sketch = {
        "id": "sk2", "kind": "sketch", "label": "two circles",
        "plane": "@builtin_plane_top",
        "entities": [
            {"id": "c1", "kind": "circle"},
            {"id": "c2", "kind": "circle"},
        ],
        "initial": {"c1": [0, 0, 10], "c2": [40, 0, 5]},
        "constraints": [
            {"id": "cc", "kind": "coincident", "a": "$c1center", "b": "@builtin_origin"},
            {"id": "cd", "kind": "diameter", "target": "$c1", "value": 20, "pos": [0, 0]},
        ],
    }
    extrude = {
        "id": "ex2", "kind": "extrude", "label": "extrude",
        "sketch": "$sk2", "distance": 10, "direction": "normal",
    }
    return {"features": [sketch, extrude]}


def _circle_rim_queries(body: dict) -> list:
    return [
        q for ed, q in zip(body["edges"], body["edge_queries"])
        if ed["kind"] == "circle"
    ]


def _is_filleted(body: dict) -> bool:
    # A plain cylinder body has 3 edges (1 seam + 2 rims); filleting adds more.
    return len(body["edges"]) > 3


def test_fillet_applies_to_the_second_body():
    """Regression: one extrude can yield two disjoint bodies (two circles ->
    two cylinders). A fillet selecting edges on the SECOND body must fillet
    that body, not silently pick the first body (or fail to resolve).

    Bug: _apply_edge_feature used the first body in the store and ignored the
    @body_<id> the edge queries referenced.
    """
    from oversolved.kernel.builder import build

    spec = _two_circle_extrude_spec()
    r0 = build(spec)
    assert r0["result"]["ex2"]["status"] == "ok"
    assert "body_ex2" in r0["bodies"] and "body_ex2_1" in r0["bodies"], (
        f"expected two bodies, got {list(r0['bodies'])}"
    )

    second = r0["bodies"]["body_ex2_1"]
    spec["features"].append({
        "id": "fil2", "kind": "fillet", "label": "Fillet",
        "edges": _circle_rim_queries(second), "radius": 1.0,
    })
    r = build(spec)
    assert r["result"]["fil2"]["status"] == "ok", (
        f"fillet failed: {r['result']['fil2'].get('exception')}"
    )

    assert _is_filleted(r["bodies"]["body_ex2_1"]), "second body was not filleted"
    assert not _is_filleted(r["bodies"]["body_ex2"]), (
        "first body must stay untouched when only the second body's edges are selected"
    )


def test_fillet_applies_across_both_bodies():
    """A fillet selecting edges from both bodies fillets each body."""
    from oversolved.kernel.builder import build

    spec = _two_circle_extrude_spec()
    r0 = build(spec)
    edges = (
        _circle_rim_queries(r0["bodies"]["body_ex2"])[:1]
        + _circle_rim_queries(r0["bodies"]["body_ex2_1"])[:1]
    )
    spec["features"].append({
        "id": "fil2", "kind": "fillet", "label": "Fillet",
        "edges": edges, "radius": 1.0,
    })
    r = build(spec)
    assert r["result"]["fil2"]["status"] == "ok", (
        f"fillet failed: {r['result']['fil2'].get('exception')}"
    )
    assert _is_filleted(r["bodies"]["body_ex2"]), "first body not filleted"
    assert _is_filleted(r["bodies"]["body_ex2_1"]), "second body not filleted"


def test_fillet_edge_created_by_modifier():
    """Fillet on an edge whose @created_by differs from body.created_by must
    resolve correctly via modifier-aware hash lookup.

    When a revolve (or other boolean modifier) adds geometry to an existing
    extruded body, the builder rewrites the @created_by tag in the new edge
    queries from body.created_by to body.modified_by[-1] (builder.py:612-629).
    The fillet resolver must match by using the same modifier-aware created_by.
    Before the fix, it used body.created_by unconditionally, causing the
    hash-based direct lookup to fail and falling through to the unstable
    body-scoped type fallback.

    Regression test for: bugreports/filet_filets_wrong_edge_20260522_175137.md
    """
    from oversolved.kernel.builder import build
    from oversolved.kernel.query import _parse_ancestry
    from solver_helpers import rect_sketch_spec, assert_mesh_valid

    sketch = rect_sketch_spec(w=5, h=5, sketch_id='sk1')
    spec = {
        'features': [
            sketch,
            {'id': 'ex1', 'kind': 'extrude', 'label': 'Extrude',
             'sketch': '$sk1', 'distance': 5, 'direction': 'normal'},
        ],
    }
    build(spec)

    # Revolve that adds geometry to the existing extruded body.
    # The boolean union creates new edges that get @created_by=rev1.
    spec['features'].append({
        'id': 'rev1', 'kind': 'revolve', 'label': 'Revolve',
        'sketch': '$sk1', 'angle': 90.0,
        'axis_origin': [0, 0, 0], 'axis_direction': [0, 0, 1],
        'operation': 'add',
    })
    r1 = build(spec)
    edge_queries = r1['bodies']['body_ex1'].get('edge_queries', [])
    assert len(edge_queries) > 0, "no edge_queries after revolve"

    # Locate a hash-based 3-ID query whose @created_by is the modifier (rev1).
    modifier_edge_query = None
    for q in edge_queries:
        if q.startswith('?'):
            try:
                ids, _ = _parse_ancestry(q)
                if len(ids) >= 2 and ids[1] == '@rev1':
                    modifier_edge_query = q
                    break
            except Exception:
                continue

    if modifier_edge_query is None:
        # The revolve may not have created new B-rep edges in this specific
        # geometry. Skip the test gracefully.
        return

    spec['features'].append({
        'id': 'fillet1', 'kind': 'fillet', 'label': 'Fillet',
        'edges': [modifier_edge_query],
        'radius': 0.5,
    })
    r = build(spec)
    assert r['result']['fillet1']['status'] == 'ok', \
        "fillet on modifier-created edge failed: %s" % r['result']['fillet1'].get('exception')
    mesh = r['bodies']['body_ex1']['mesh']
    assert_mesh_valid(mesh)


#  ── Geometry-aware routing & partial-failure tests ──


def _two_box_spec():
    """Two disjoint boxes from two independent extrudes -> body_exA, body_exB."""
    from solver_helpers import rect_sketch_spec, extrude_spec

    skA = rect_sketch_spec(w=10, h=10, sketch_id='skA', plane='@builtin_plane_top')
    skB = rect_sketch_spec(w=10, h=10, sketch_id='skB', plane='@builtin_plane_top')
    skB['initial'] = {
        eid: [c[0] + 30, c[1], c[2] + 30, c[3]]
        for eid, c in skB['initial'].items()
    }
    exA = extrude_spec('skA', 'exA', 5, operation='new')
    exB = extrude_spec('skB', 'exB', 5, operation='new')
    return {'features': [skA, skB, exA, exB]}


def test_fillet_follows_geometry_when_body_token_stale():
    """A stale @body_<id> token must not misroute the fillet.

    Repro of bugreports/assymetric_inconsistent_rebuild: an edge query whose
    body token names the wrong body must still fillet whichever body actually
    owns the matching edge geometry (matched by gedge hash).
    """
    from oversolved.kernel.builder import build

    spec = _two_box_spec()
    r0 = build(spec)
    qB = r0['bodies']['body_exB']['edge_queries'][0]
    assert '@body_exB' in qB
    # Swap the body token to the wrong body; keep the gedge hash intact.
    stale_q = qB.replace('@body_exB', '@body_exA')
    assert '@body_exA' in stale_q and '@body_exB' not in stale_q

    spec['features'].append({
        'id': 'fil', 'kind': 'fillet', 'label': 'F',
        'edges': [stale_q], 'radius': 1.0,
    })
    r = build(spec)
    assert r['result']['fil']['status'] == 'ok', r['result']['fil'].get('exception')
    assert r['result']['fil']['body_ids'] == ['body_exB'], \
        "fillet must follow geometry to body_exB, not the stale token's body_exA"


def test_fillet_asymmetry_delete_upstream_extrude():
    """Deleting an unrelated body must not break a fillet; deleting its own must.

    Symmetry property from bugreports/assymetric_inconsistent_rebuild.
    """
    from oversolved.kernel.builder import build

    spec = _two_box_spec()
    r0 = build(spec)
    qB = r0['bodies']['body_exB']['edge_queries'][0]
    filB = {'id': 'filB', 'kind': 'fillet', 'label': 'B',
            'edges': [qB], 'radius': 1.0}

    from solver_helpers import rect_sketch_spec, extrude_spec
    skB = rect_sketch_spec(w=10, h=10, sketch_id='skB', plane='@builtin_plane_top')
    skB['initial'] = {
        eid: [c[0] + 30, c[1], c[2] + 30, c[3]]
        for eid, c in skB['initial'].items()
    }
    exB = extrude_spec('skB', 'exB', 5, operation='new')
    skA = rect_sketch_spec(w=10, h=10, sketch_id='skA', plane='@builtin_plane_top')
    exA = extrude_spec('skA', 'exA', 5, operation='new')

    # Delete exA (unrelated): filB still succeeds.
    r_del_a = build({'features': [skB, exB, filB]})
    assert r_del_a['result']['filB']['status'] == 'ok', \
        r_del_a['result']['filB'].get('exception')

    # Delete exB (its own body): filB fails, but the build still completes.
    r_del_b = build({'features': [skA, exA, filB]})
    assert r_del_b['result']['filB']['status'] == 'exception'
    assert r_del_b['result']['exA']['status'] == 'ok'


def test_fillet_partial_when_some_edges_unresolvable():
    """One resolvable + one missing edge -> partial: body filleted, feature red."""
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    r0 = build(spec)
    valid_q = r0['bodies']['body_ex1']['edge_queries'][0]

    spec['features'].append({
        'id': 'fil', 'kind': 'fillet', 'label': 'F',
        'edges': [valid_q, '?body_nonexistent:edge:0'], 'radius': 1.0,
    })
    r = build(spec)
    assert r['result']['fil']['status'] == 'partial'
    assert r['result']['fil']['body_ids'] == ['body_ex1']
    assert 'could not be resolved' in r['result']['fil'].get('exception', '')
    # Partial status must not block downstream registration of the body.
    assert r['bodies']['body_ex1'].get('edge_queries')


def test_fillet_all_edges_missing_is_hard_exception():
    """If nothing resolves, the fillet hard-fails."""
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    spec['features'].append({
        'id': 'fil', 'kind': 'fillet', 'label': 'F',
        'edges': ['?body_nonexistent:edge:0'], 'radius': 1.0,
    })
    r = build(spec)
    assert r['result']['fil']['status'] == 'exception'
    assert 'no edges resolved' in r['result']['fil'].get('exception', '')
