import importlib
import pytest

pytestmark = [
    pytest.mark.skipif(
        not importlib.util.find_spec("cadquery"), reason="cadquery not installed"
    ),
    pytest.mark.skipif(
        not importlib.util.find_spec("vtkmodules"), reason="vtkmodules not installed"
    ),
]


#  ── Fillet tests ──


def test_fillet_single_edge():
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec, assert_mesh_valid

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    spec["features"].append({
        "id": "fillet1",
        "kind": "fillet",
        "label": "Fillet",
        "edges": ["?body_ex1:edge:0"],
        "radius": 1.0,
    })
    r = build(spec)
    assert r["result"]["fillet1"]["status"] == "ok", f"build failed: {r['result']['fillet1'].get('exception')}"
    mesh = r["bodies"]["body_ex1"]["mesh"]
    assert_mesh_valid(mesh)


def test_fillet_multiple_edges():
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec, assert_mesh_valid

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    spec["features"].append({
        "id": "fillet1",
        "kind": "fillet",
        "label": "Fillet",
        "edges": ["?body_ex1:edge:0", "?body_ex1:edge:1"],
        "radius": 1.0,
    })
    r = build(spec)
    assert r["result"]["fillet1"]["status"] == "ok"
    mesh = r["bodies"]["body_ex1"]["mesh"]
    assert_mesh_valid(mesh)


def test_fillet_zero_radius_errors():
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    spec["features"].append({
        "id": "fillet1",
        "kind": "fillet",
        "label": "Fillet",
        "edges": ["?body_ex1:edge:0"],
        "radius": 0,
    })
    r = build(spec)
    assert r["result"]["fillet1"]["status"] == "exception"
    assert "radius must be positive" in r["result"]["fillet1"].get("exception", "")


def test_fillet_negative_radius_errors():
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    spec["features"].append({
        "id": "fillet1",
        "kind": "fillet",
        "label": "Fillet",
        "edges": ["?body_ex1:edge:0"],
        "radius": -1,
    })
    r = build(spec)
    assert r["result"]["fillet1"]["status"] == "exception"
    assert "radius must be positive" in r["result"]["fillet1"].get("exception", "")


def test_fillet_empty_edges_errors():
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    spec["features"].append({
        "id": "fillet1",
        "kind": "fillet",
        "label": "Fillet",
        "edges": [],
        "radius": 1.0,
    })
    r = build(spec)
    assert r["result"]["fillet1"]["status"] == "exception"
    assert "requires at least one edge" in r["result"]["fillet1"].get("exception", "")


def test_fillet_3id_ancestry_query():
    """Fillet edge queries stored in '3-ID' format (body_id + created_by + body_id)
    must resolve correctly. This is the format generated by solid_to_edges(body_id=...).
    """
    from oversolved.kernel.builder import build
    from oversolved.kernel.query import make_ancestry_query
    from solver_helpers import full_rect_extrude_spec, assert_mesh_valid

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    q3 = make_ancestry_query(
        ["@body_ex1edge0", "@ex1", "@body_ex1"], "straightedge"
    )
    spec["features"].append({
        "id": "fillet1",
        "kind": "fillet",
        "label": "Fillet",
        "edges": [q3],
        "radius": 1.0,
    })
    r = build(spec)
    assert r["result"]["fillet1"]["status"] == "ok", \
        f"3-ID ancestry query failed: {r['result']['fillet1'].get('exception')}"
    mesh = r["bodies"]["body_ex1"]["mesh"]
    assert_mesh_valid(mesh)


def test_fillet_roundtrip_via_edge_queries():
    """Simulate the real frontend round-trip: edge_queries from build output
    are fed back as fillet edge input. This verifies that queries generated
    by solid_to_edges(body_id=...) can be consumed by _resolve_fillet_edges().
    """
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec, assert_mesh_valid

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    r0 = build(spec)
    edge_queries = r0["bodies"]["body_ex1"].get("edge_queries", [])
    assert len(edge_queries) > 0, "no edge_queries in build output"

    spec["features"].append({
        "id": "fillet1",
        "kind": "fillet",
        "label": "Fillet",
        "edges": [edge_queries[0]],
        "radius": 1.0,
    })
    r = build(spec)
    assert r["result"]["fillet1"]["status"] == "ok", \
        f"round-trip fillet failed with query {edge_queries[0]!r}: {r['result']['fillet1'].get('exception')}"
    mesh = r["bodies"]["body_ex1"]["mesh"]
    assert_mesh_valid(mesh)


def test_fillet_chain_after_extrude():
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec, assert_mesh_valid

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    spec["features"].append({
        "id": "fillet1",
        "kind": "fillet",
        "label": "Fillet",
        "edges": ["?body_ex1:edge:0"],
        "radius": 1.0,
    })
    r = build(spec)
    assert r["result"]["fillet1"]["status"] == "ok"
    mesh = r["bodies"]["body_ex1"]["mesh"]
    assert_mesh_valid(mesh)


def test_fillet_updates_body():
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    r_before = build(spec)
    verts_before = r_before["bodies"]["body_ex1"]["mesh"]["vertices"]

    spec["features"].append({
        "id": "fillet1",
        "kind": "fillet",
        "label": "Fillet",
        "edges": ["?body_ex1:edge:0"],
        "radius": 2.0,
    })
    r_after = build(spec)
    verts_after = r_after["bodies"]["body_ex1"]["mesh"]["vertices"]

    assert len(verts_after) > len(verts_before)


#  ── Chamfer tests  ──


def test_chamfer_single_edge():
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec, assert_mesh_valid

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    spec["features"].append({
        "id": "chamfer1",
        "kind": "chamfer",
        "label": "Chamfer",
        "edges": ["?body_ex1:edge:0"],
        "distance": 1.0,
    })
    r = build(spec)
    assert r["result"]["chamfer1"]["status"] == "ok"
    mesh = r["bodies"]["body_ex1"]["mesh"]
    assert_mesh_valid(mesh)


def test_chamfer_multiple_edges():
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec, assert_mesh_valid

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    spec["features"].append({
        "id": "chamfer1",
        "kind": "chamfer",
        "label": "Chamfer",
        "edges": ["?body_ex1:edge:0", "?body_ex1:edge:1"],
        "distance": 1.0,
    })
    r = build(spec)
    assert r["result"]["chamfer1"]["status"] == "ok"
    mesh = r["bodies"]["body_ex1"]["mesh"]
    assert_mesh_valid(mesh)


def test_chamfer_distance_zero_errors():
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    spec["features"].append({
        "id": "chamfer1",
        "kind": "chamfer",
        "label": "Chamfer",
        "edges": ["?body_ex1:edge:0"],
        "distance": 0,
    })
    r = build(spec)
    assert r["result"]["chamfer1"]["status"] == "exception"
    assert "distance must be positive" in r["result"]["chamfer1"].get("exception", "")


def test_chamfer_negative_distance_errors():
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    spec["features"].append({
        "id": "chamfer1",
        "kind": "chamfer",
        "label": "Chamfer",
        "edges": ["?body_ex1:edge:0"],
        "distance": -1,
    })
    r = build(spec)
    assert r["result"]["chamfer1"]["status"] == "exception"
    assert "distance must be positive" in r["result"]["chamfer1"].get("exception", "")


def test_chamfer_empty_edges_errors():
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    spec["features"].append({
        "id": "chamfer1",
        "kind": "chamfer",
        "label": "Chamfer",
        "edges": [],
        "distance": 1.0,
    })
    r = build(spec)
    assert r["result"]["chamfer1"]["status"] == "exception"
    assert "requires at least one edge" in r["result"]["chamfer1"].get("exception", "")


def test_chamfer_chain_after_extrude():
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec, assert_mesh_valid

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    spec["features"].append({
        "id": "chamfer1",
        "kind": "chamfer",
        "label": "Chamfer",
        "edges": ["?body_ex1:edge:0"],
        "distance": 1.0,
    })
    r = build(spec)
    assert r["result"]["chamfer1"]["status"] == "ok"
    mesh = r["bodies"]["body_ex1"]["mesh"]
    assert_mesh_valid(mesh)


def test_chamfer_updates_body():
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    r_before = build(spec)
    verts_before = r_before["bodies"]["body_ex1"]["mesh"]["vertices"]

    spec["features"].append({
        "id": "chamfer1",
        "kind": "chamfer",
        "label": "Chamfer",
        "edges": ["?body_ex1:edge:0"],
        "distance": 2.0,
    })
    r_after = build(spec)
    verts_after = r_after["bodies"]["body_ex1"]["mesh"]["vertices"]

    assert len(verts_after) > len(verts_before)


#  ── Chain tests ──


def test_fillet_then_chamfer():
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec, assert_mesh_valid

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    spec["features"].append({
        "id": "fillet1",
        "kind": "fillet",
        "label": "Fillet",
        "edges": ["?body_ex1:edge:0"],
        "radius": 1.0,
    })
    spec["features"].append({
        "id": "chamfer1",
        "kind": "chamfer",
        "label": "Chamfer",
        "edges": ["?body_ex1:edge:1"],
        "distance": 0.5,
    })
    r = build(spec)
    assert r["result"]["fillet1"]["status"] == "ok"
    assert r["result"]["chamfer1"]["status"] == "ok"
    mesh = r["bodies"]["body_ex1"]["mesh"]
    assert_mesh_valid(mesh)


def test_fillet_respects_edge_list():
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec

    spec1 = full_rect_extrude_spec(w=10, h=10, d=5)
    spec1["features"].append({
        "id": "fillet1",
        "kind": "fillet",
        "label": "Fillet",
        "edges": ["?body_ex1:edge:0"],
        "radius": 1.0,
    })
    r1 = build(spec1)
    verts1 = len(r1["bodies"]["body_ex1"]["mesh"]["vertices"])

    spec_all = full_rect_extrude_spec(w=10, h=10, d=5)
    spec_all["features"].append({
        "id": "fillet1",
        "kind": "fillet",
        "label": "Fillet",
        "edges": [f"?body_ex1:edge:{i}" for i in range(12)],
        "radius": 1.0,
    })
    r_all = build(spec_all)
    verts_all = len(r_all["bodies"]["body_ex1"]["mesh"]["vertices"])

    assert verts1 < verts_all, (
        f"single-edge fillet ({verts1}) should have fewer verts than all-edge fillet ({verts_all})"
    )


def test_fillet_body_modified_between_roundtrips():
    """Fillet using a 3-ID ancestry query that was generated before a
    body-modifying operation (e.g., another fillet) must still resolve.

    This simulates the scenario from bugreports/server_crash_20260509_215800.md
    where the fillet edge query was stored before a body-mutating operation.
    """
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    r0 = build(spec)
    edge_queries = r0["bodies"]["body_ex1"].get("edge_queries", [])
    assert len(edge_queries) > 0

    # Simulate a prior body-modifying operation (another fillet)
    spec["features"].append({
        "id": "fillet1",
        "kind": "fillet",
        "label": "Fillet 1",
        "edges": ["?body_ex1:edge:0"],
        "radius": 1.0,
    })
    # Use hash-based query from before the first fillet modified the body
    spec["features"].append({
        "id": "fillet2",
        "kind": "fillet",
        "label": "Fillet 2",
        "edges": [edge_queries[1]],
        "radius": 1.0,
    })
    r = build(spec)
    # fillet1 modifies the body shape; fillet2 should handle gracefully
    assert r["result"]["fillet2"]["status"] in ("ok", "exception"), \
        f"unexpected status: {r['result']['fillet2']}"


def test_multiple_fillet_features():
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec, assert_mesh_valid

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    spec["features"].append({
        "id": "fillet1",
        "kind": "fillet",
        "label": "Fillet 1",
        "edges": ["?body_ex1:edge:0"],
        "radius": 1.0,
    })
    spec["features"].append({
        "id": "fillet2",
        "kind": "fillet",
        "label": "Fillet 2",
        "edges": ["?body_ex1:edge:1"],
        "radius": 0.5,
    })
    r = build(spec)
    assert r["result"]["fillet1"]["status"] == "ok"
    assert r["result"]["fillet2"]["status"] == "ok"
    mesh = r["bodies"]["body_ex1"]["mesh"]
    assert_mesh_valid(mesh)


# ─── fix-143: _solve_transform module ownership ───

def test_solve_transform_not_in_fillet_module():
    """_solve_transform must not be defined in the fillet/chamfer module."""
    import oversolved.kernel.solver_features_fillet_chamfer as fc_mod
    assert not hasattr(fc_mod, "_solve_transform"), (
        "_solve_transform should only live in solver_features_transform_mirror"
    )


def test_solve_transform_resolves_from_correct_module():
    """_solve_transform must be defined in solver_features_transform_mirror."""
    import oversolved.kernel.solver_features_transform_mirror as tm
    assert hasattr(tm, "_solve_transform")


# ─── fix-144: chamfer kind shadowed by feature kind ───

def test_chamfer_distance_mode_unchanged():
    """Default distance chamfer still works after the kind-shadow fix."""
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec, assert_mesh_valid

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    spec["features"].append({
        "id": "ch1",
        "kind": "chamfer",
        "label": "Chamfer",
        "edges": ["?body_ex1:edge:0"],
        "chamfer": {"distance": 1.0, "kind": "distance"},
    })
    r = build(spec)
    assert r["result"]["ch1"]["status"] == "ok", r["result"]["ch1"].get("exception")
    assert_mesh_valid(r["bodies"]["body_ex1"]["mesh"])


def test_chamfer_angle_distance_mode():
    """Chamfer with kind=angle_distance in the sub-dict must not fall back to distance mode."""
    import unittest.mock as mock
    from oversolved.kernel.builder import build
    from solver_helpers import full_rect_extrude_spec

    spec = full_rect_extrude_spec(w=10, h=10, d=5)
    spec["features"].append({
        "id": "ch1",
        "kind": "chamfer",
        "label": "Chamfer",
        "edges": ["?body_ex1:edge:0"],
        "chamfer": {"distance": 1.0, "angle": 30.0, "kind": "angle_distance"},
    })

    with mock.patch("oversolved.kernel.solver_features_fillet_chamfer.apply_chamfer", wraps=__import__(
        "oversolved.kernel.solver_features_fillet_chamfer", fromlist=["apply_chamfer"]
    ).apply_chamfer) as mock_chamfer:
        r = build(spec)

    assert r["result"]["ch1"]["status"] == "ok", r["result"]["ch1"].get("exception")
    assert mock_chamfer.called
    _, kwargs = mock_chamfer.call_args
    assert kwargs.get("kind") == "angle_distance", (
        f"apply_chamfer was called with kind={kwargs.get('kind')!r}, expected 'angle_distance'"
    )
